#GATEWAY MASTER PORT IS 2331 - SWAP THIS IN WHEN PUSHING TO MASTER
#GATEWAY DEVELOPMENt PORT IS 8212 - THIS SHOULD BE ACTIVE BY DEFAULT


server:  
  port: 8212
  
spring:
  application:    
    name: gatewayservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-3-236-121-83.compute-1.amazonaws.com:8762/eureka


#EUREKA MASTER PORT IS 2329 - SWAP THIS IN WHEN PUSHING TO MASTER
#EUREKA DEVELOPMENT PORT IS 8762 - THIS SHOULD BE ACTIVE BY DEFAULT

zuul:
  routes:    
    eureka:
      path: /eureka/**
      url: http://ec2-3-235-74-191.compute-1.amazonaws.com:8762/
    data:
      path: /data/**
      service-id: dataservice
    reports:
      path: /reports/**
      service-id: reportsservice
      
       
      