server:  
  port: 8212
  
spring:
  application:    
    name: gatewayservice

zuul:
  routes:    
    eureka:
      path: /eureka/**
      url: http://ec2-3-236-121-83.compute-1.amazonaws.com:8762/
    data:
      path: /data/**
      service-id: dataservice
    reports:
      path: /reports/**
      service-id: reportsservice